ChangeCalculator: ChangeCalculator.cpp
	g++ ChangeCalculator.cpp -o ChangeCalculator
	./ChangeCalculator

IntegerComplexity1: IntegerComplexity1.cpp
	g++ IntegerComplexity1.cpp -o IntegerComplexity1
	./IntegerComplexity1

TalkingClock: TalkingClock.c
	gcc TalkingClock.c -o TalkingClock
	./TalkingClock

WhatDay: WhatDay.c
	gcc WhatDay.c -o WhatDay
	./WhatDay

clean:
	rm -rf IntegerComplexity1
	rm -rf ChangeCalculator
	rm -rf TalkingClock
	rm -rf WhatDay
